namespace ChangeDetection.Shared.Dtos;

/// <summary>
/// Request to run the watch setup pipeline.
/// </summary>
public class RunPipelineRequest
{
    /// <summary>
    /// User's natural language input describing what to watch.
    /// </summary>
    public required string Input { get; set; }

    /// <summary>
    /// Maximum iterations for selector validation. Defaults to 3.
    /// </summary>
    public int? MaxIterations { get; set; }

    /// <summary>
    /// Minimum confidence threshold (0-1). Defaults to 0.8.
    /// </summary>
    public double? ConfidenceThreshold { get; set; }
}

/// <summary>
/// Response from the watch setup pipeline.
/// </summary>
public class RunPipelineResponse
{
    /// <summary>
    /// Whether the pipeline completed successfully.
    /// </summary>
    public bool IsSuccess { get; set; }

    /// <summary>
    /// Current stage of the pipeline.
    /// </summary>
    public string Stage { get; set; } = string.Empty;

    /// <summary>
    /// Number of iterations performed.
    /// </summary>
    public int IterationCount { get; set; }

    /// <summary>
    /// Extracted URLs from the input.
    /// </summary>
    public List<string> ExtractedUrls { get; set; } = [];

    /// <summary>
    /// Best selector candidate found.
    /// </summary>
    public SelectorCandidateDto? BestSelector { get; set; }

    /// <summary>
    /// All selector candidates considered.
    /// </summary>
    public List<SelectorCandidateDto> AllSelectors { get; set; } = [];

    /// <summary>
    /// LLM's analysis of the page content.
    /// </summary>
    public ContentAnalysisDto? ContentAnalysis { get; set; }

    /// <summary>
    /// Ready-to-use watch configuration.
    /// </summary>
    public ParsedWatchRequestDto? WatchConfig { get; set; }

    /// <summary>
    /// Error message if pipeline failed.
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// Detailed logs from each stage.
    /// </summary>
    public List<string> Logs { get; set; } = [];
}

/// <summary>
/// A selector candidate generated by the pipeline.
/// </summary>
public class SelectorCandidateDto
{
    /// <summary>
    /// Type of selector: XPath, CssSelector, Regex.
    /// </summary>
    public required string Type { get; set; }

    /// <summary>
    /// The selector expression.
    /// </summary>
    public required string Expression { get; set; }

    /// <summary>
    /// Confidence score (0-1).
    /// </summary>
    public double Confidence { get; set; }

    /// <summary>
    /// Whether this selector has been validated.
    /// </summary>
    public bool IsValidated { get; set; }

    /// <summary>
    /// Number of matches found during validation.
    /// </summary>
    public int MatchCount { get; set; }

    /// <summary>
    /// Sample of extracted text from validation.
    /// </summary>
    public string? SampleText { get; set; }

    /// <summary>
    /// LLM's explanation of why this selector was chosen.
    /// </summary>
    public string? Reasoning { get; set; }
}

/// <summary>
/// LLM's analysis of the page content.
/// </summary>
public class ContentAnalysisDto
{
    /// <summary>
    /// Type of page detected (e.g., EventListing, ProductPage, NewsArticle).
    /// </summary>
    public string? PageType { get; set; }

    /// <summary>
    /// LLM's understanding of what the user wants to monitor.
    /// </summary>
    public string? UserIntent { get; set; }

    /// <summary>
    /// Key content sections identified on the page.
    /// </summary>
    public List<ContentSectionDto> ContentSections { get; set; } = [];

    /// <summary>
    /// Recommended monitoring approach.
    /// </summary>
    public string? RecommendedApproach { get; set; }
}

/// <summary>
/// A content section identified on the page.
/// </summary>
public class ContentSectionDto
{
    /// <summary>
    /// Name of the section.
    /// </summary>
    public required string Name { get; set; }

    /// <summary>
    /// Description of what this section contains.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Suggested selector for this section.
    /// </summary>
    public string? SuggestedSelector { get; set; }

    /// <summary>
    /// Relevance score (0-1) to user's intent.
    /// </summary>
    public double Relevance { get; set; }
}

// ============================================================================
// Streaming DTOs for Multi-Agent Watch Setup Pipeline
// ============================================================================

/// <summary>
/// Request to start an interactive watch setup session.
/// </summary>
public class StartSetupSessionRequest
{
    /// <summary>
    /// Initial user message (optional, can send first message after session starts).
    /// </summary>
    public string? InitialMessage { get; set; }
}

/// <summary>
/// Response when a setup session is created.
/// </summary>
public class StartSetupSessionResponse
{
    /// <summary>
    /// Session ID for subsequent messages.
    /// </summary>
    public required Guid SessionId { get; set; }

    /// <summary>
    /// When the session was created.
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; }
}

/// <summary>
/// Request to send a message in an existing setup session.
/// </summary>
public class SendSetupMessageRequest
{
    /// <summary>
    /// The session to send the message to.
    /// </summary>
    public required Guid SessionId { get; set; }

    /// <summary>
    /// User's message content.
    /// </summary>
    public required string Message { get; set; }
}

/// <summary>
/// A streaming chunk from the multi-agent setup pipeline.
/// Sent via SignalR for real-time updates.
/// </summary>
public class AgentStreamChunkDto
{
    /// <summary>
    /// Name of the agent producing this chunk.
    /// </summary>
    public required string AgentName { get; set; }

    /// <summary>
    /// Type of content in this chunk.
    /// </summary>
    public required string ChunkType { get; set; }

    /// <summary>
    /// The actual content.
    /// </summary>
    public required string Content { get; set; }

    /// <summary>
    /// Optional confidence score (0-1).
    /// </summary>
    public double? Confidence { get; set; }

    /// <summary>
    /// Whether this content should be collapsed by default in UI.
    /// Thinking/reasoning chunks are typically collapsible.
    /// </summary>
    public bool IsCollapsible { get; set; }

    /// <summary>
    /// Timestamp when this chunk was created.
    /// </summary>
    public DateTimeOffset Timestamp { get; set; }
}

/// <summary>
/// Types of chunk content for serialization.
/// </summary>
public static class ChunkTypeNames
{
    public const string Thinking = "thinking";
    public const string Intermediate = "intermediate";
    public const string Question = "question";
    public const string Result = "result";
    public const string Validation = "validation";
    public const string Error = "error";
    public const string Started = "started";
    public const string Completed = "completed";
}

/// <summary>
/// Agent names for serialization.
/// </summary>
public static class AgentNamesDtos
{
    public const string UrlExtraction = "url-extraction";
    public const string ContentAnalysis = "content-analysis";
    public const string SelectorGeneration = "selector-generation";
    public const string Validation = "validation";
    public const string Synthesis = "synthesis";
    public const string Resolution = "resolution";
    public const string SchemaDiscovery = "schema-discovery";
}

/// <summary>
/// Setup stage names for serialization.
/// </summary>
public static class SetupStageNames
{
    public const string Initial = "initial";
    public const string Processing = "processing";
    public const string UrlSelection = "url-selection";
    public const string Fetching = "fetching";
    public const string Analyzing = "analyzing";
    public const string SelectorRefinement = "selector-refinement";
    public const string SchemaDiscovery = "schema-discovery";
    public const string SchemaRefinement = "schema-refinement";
    public const string Confirmation = "confirmation";
    public const string Completed = "completed";
    public const string Error = "error";
}

/// <summary>
/// Current state of a setup session.
/// </summary>
public class SetupSessionStateDto
{
    /// <summary>
    /// Session ID.
    /// </summary>
    public required Guid SessionId { get; set; }

    /// <summary>
    /// Current stage of setup.
    /// </summary>
    public required string Stage { get; set; }

    /// <summary>
    /// Whether waiting for user input.
    /// </summary>
    public bool AwaitingInput { get; set; }

    /// <summary>
    /// The current question/prompt awaiting user response (when AwaitingInput is true).
    /// </summary>
    public string? CurrentPrompt { get; set; }

    /// <summary>
    /// Partial configuration built so far.
    /// </summary>
    public PartialWatchConfigurationDto? Configuration { get; set; }

    /// <summary>
    /// Options currently presented to user.
    /// </summary>
    public List<PresentedOptionDto> PresentedOptions { get; set; } = [];
}

/// <summary>
/// Partial watch configuration being built during setup.
/// </summary>
public class PartialWatchConfigurationDto
{
    public string? Url { get; set; }
    public string? Name { get; set; }
    public string? Description { get; set; }
    public string? CssSelector { get; set; }
    public string? XPathSelector { get; set; }
    public bool? UseJavaScript { get; set; }
    public string? CheckInterval { get; set; }
    public List<string> Tags { get; set; } = [];
    public double? Confidence { get; set; }

    /// <summary>
    /// Discovered schema for object extraction (if list-type content).
    /// </summary>
    public DiscoveredSchemaDto? DiscoveredSchema { get; set; }

    /// <summary>
    /// Whether schema extraction should be enabled.
    /// </summary>
    public bool? SchemaEnabled { get; set; }
}

/// <summary>
/// An option presented to the user.
/// </summary>
public class PresentedOptionDto
{
    /// <summary>
    /// Unique identifier for this option.
    /// </summary>
    public required string OptionId { get; set; }

    /// <summary>
    /// Text shown to the user.
    /// </summary>
    public required string DisplayText { get; set; }

    /// <summary>
    /// Preview of what selecting this option means.
    /// </summary>
    public string? Preview { get; set; }

    /// <summary>
    /// Whether this is the recommended option.
    /// </summary>
    public bool IsRecommended { get; set; }
}

/// <summary>
/// Final setup completion response.
/// </summary>
public class SetupCompletedDto
{
    /// <summary>
    /// Session that completed.
    /// </summary>
    public required Guid SessionId { get; set; }

    /// <summary>
    /// The created watch ID.
    /// </summary>
    public Guid? WatchId { get; set; }

    /// <summary>
    /// Final configuration used.
    /// </summary>
    public PartialWatchConfigurationDto? Configuration { get; set; }

    /// <summary>
    /// Summary message for the user.
    /// </summary>
    public string? Summary { get; set; }
}

// ============================================================================
// Schema Discovery DTOs
// ============================================================================

/// <summary>
/// Schema discovered by LLM during setup.
/// Presented to user for confirmation/refinement.
/// </summary>
public class DiscoveredSchemaDto
{
    /// <summary>
    /// CSS or XPath selector for the repeating item container.
    /// </summary>
    public required string ItemSelector { get; set; }

    /// <summary>
    /// Discovered fields with their selectors and types.
    /// </summary>
    public List<DiscoveredFieldDto> Fields { get; set; } = [];

    /// <summary>
    /// Fields inferred to uniquely identify objects (for diff matching).
    /// </summary>
    public List<string> InferredIdentityFields { get; set; } = [];

    /// <summary>
    /// Overall confidence in the schema discovery (0-1).
    /// </summary>
    public double Confidence { get; set; }

    /// <summary>
    /// Number of items found on the page matching the schema.
    /// </summary>
    public int SampleItemCount { get; set; }

    /// <summary>
    /// LLM's explanation of the discovered structure.
    /// </summary>
    public string? Explanation { get; set; }

    /// <summary>
    /// Content type detected (EventList, ProductListing, etc.).
    /// </summary>
    public string? ContentType { get; set; }
}

/// <summary>
/// A field discovered during schema discovery.
/// </summary>
public class DiscoveredFieldDto
{
    /// <summary>
    /// Suggested field name.
    /// </summary>
    public required string Name { get; set; }

    /// <summary>
    /// Inferred field type: String, Date, Url, Number, Image, Html.
    /// </summary>
    public required string Type { get; set; }

    /// <summary>
    /// Selector relative to item container.
    /// </summary>
    public required string Selector { get; set; }

    /// <summary>
    /// Whether the field appears in all items (required).
    /// </summary>
    public bool IsRequired { get; set; }

    /// <summary>
    /// Whether LLM suggests this as an identity field.
    /// </summary>
    public bool IsIdentityField { get; set; }

    /// <summary>
    /// Sample values extracted from the page.
    /// </summary>
    public List<string> SampleValues { get; set; } = [];

    /// <summary>
    /// Confidence in this field's detection (0-1).
    /// </summary>
    public double Confidence { get; set; }

    /// <summary>
    /// LLM's explanation for this field.
    /// </summary>
    public string? Reasoning { get; set; }
}

/// <summary>
/// User's response to schema discovery for refinement.
/// </summary>
public class SchemaRefinementRequest
{
    /// <summary>
    /// Session ID.
    /// </summary>
    public required Guid SessionId { get; set; }

    /// <summary>
    /// User-edited fields (can rename, change types, toggle identity).
    /// </summary>
    public List<SchemaFieldEditDto> Fields { get; set; } = [];

    /// <summary>
    /// Fields to exclude from extraction.
    /// </summary>
    public List<string> ExcludedFieldNames { get; set; } = [];

    /// <summary>
    /// User-specified identity field names (overrides LLM inference).
    /// </summary>
    public List<string>? IdentityFieldOverrides { get; set; }

    /// <summary>
    /// Whether to enable schema extraction for this watch.
    /// </summary>
    public bool EnableSchema { get; set; } = true;
}

/// <summary>
/// User edit to a schema field.
/// </summary>
public class SchemaFieldEditDto
{
    /// <summary>
    /// Original field name from discovery.
    /// </summary>
    public required string OriginalName { get; set; }

    /// <summary>
    /// New name (if renamed).
    /// </summary>
    public string? NewName { get; set; }

    /// <summary>
    /// New type (if changed).
    /// </summary>
    public string? NewType { get; set; }

    /// <summary>
    /// Whether to mark as identity field.
    /// </summary>
    public bool? IsIdentityField { get; set; }

    /// <summary>
    /// Whether the field is required.
    /// </summary>
    public bool? IsRequired { get; set; }
}

// ============================================================================
// Object Extraction DTOs
// ============================================================================

/// <summary>
/// An extracted object from a watched page.
/// </summary>
public class ExtractedObjectDto
{
    /// <summary>
    /// Unique identity string computed from identity fields.
    /// </summary>
    public required string Identity { get; set; }

    /// <summary>
    /// Field name-value pairs.
    /// </summary>
    public Dictionary<string, string> Fields { get; set; } = [];

    /// <summary>
    /// Original HTML of the item (for debugging).
    /// </summary>
    public string? SourceHtml { get; set; }

    /// <summary>
    /// Selector index (position in the list).
    /// </summary>
    public int Index { get; set; }
}

/// <summary>
/// Result of diffing two sets of extracted objects.
/// </summary>
public class ObjectDiffResultDto
{
    /// <summary>
    /// Objects that are new (not in previous snapshot).
    /// </summary>
    public List<ExtractedObjectDto> AddedObjects { get; set; } = [];

    /// <summary>
    /// Objects that were removed (not in current snapshot).
    /// </summary>
    public List<ExtractedObjectDto> RemovedObjects { get; set; } = [];

    /// <summary>
    /// Objects that exist in both but have changed fields.
    /// </summary>
    public List<ObjectChangeDto> ChangedObjects { get; set; } = [];

    /// <summary>
    /// Objects with ambiguous identity (multiple matches possible).
    /// </summary>
    public List<AmbiguousIdentityDto> AmbiguousIdentities { get; set; } = [];

    /// <summary>
    /// Total number of objects in current snapshot.
    /// </summary>
    public int TotalCurrentObjects { get; set; }

    /// <summary>
    /// Total number of objects in previous snapshot.
    /// </summary>
    public int TotalPreviousObjects { get; set; }
}

/// <summary>
/// A change within a single object's fields.
/// </summary>
public class ObjectChangeDto
{
    /// <summary>
    /// The object's identity.
    /// </summary>
    public required string Identity { get; set; }

    /// <summary>
    /// Field-level changes.
    /// </summary>
    public List<FieldChangeDto> FieldChanges { get; set; } = [];

    /// <summary>
    /// LLM-scored importance (0-1) if enabled.
    /// </summary>
    public double? Importance { get; set; }

    /// <summary>
    /// LLM reasoning for importance score.
    /// </summary>
    public string? ImportanceReasoning { get; set; }
}

/// <summary>
/// A change to a single field within an object.
/// </summary>
public class FieldChangeDto
{
    /// <summary>
    /// Name of the changed field.
    /// </summary>
    public required string FieldName { get; set; }

    /// <summary>
    /// Previous value.
    /// </summary>
    public string? OldValue { get; set; }

    /// <summary>
    /// New value.
    /// </summary>
    public string? NewValue { get; set; }
}

/// <summary>
/// An ambiguous identity situation requiring user resolution.
/// </summary>
public class AmbiguousIdentityDto
{
    /// <summary>
    /// The identity string that matches multiple objects.
    /// </summary>
    public required string Identity { get; set; }

    /// <summary>
    /// Objects from previous snapshot with this identity.
    /// </summary>
    public List<ExtractedObjectDto> PreviousMatches { get; set; } = [];

    /// <summary>
    /// Objects from current snapshot with this identity.
    /// </summary>
    public List<ExtractedObjectDto> CurrentMatches { get; set; } = [];

    /// <summary>
    /// LLM's suggestion for resolution (if available).
    /// </summary>
    public string? SuggestedResolution { get; set; }
}

/// <summary>
/// User resolution for an ambiguous identity conflict.
/// </summary>
public class IdentityResolutionDto
{
    /// <summary>
    /// The identity string being resolved.
    /// </summary>
    public required string Identity { get; set; }

    /// <summary>
    /// Resolution choice: "treat-as-different", "treat-as-same", "ignore".
    /// </summary>
    public required string Resolution { get; set; }
}

// ============================================================================
// Flow State DTOs (for Setup Flow Page)
// ============================================================================

/// <summary>
/// Status of a flow state entry.
/// </summary>
public enum FlowStateStatus
{
    /// <summary>
    /// Stage has not started yet.
    /// </summary>
    Pending,

    /// <summary>
    /// Stage is currently in progress.
    /// </summary>
    InProgress,

    /// <summary>
    /// Stage completed successfully.
    /// </summary>
    Completed,

    /// <summary>
    /// Stage failed.
    /// </summary>
    Failed,

    /// <summary>
    /// Recovery attempt in progress.
    /// </summary>
    Recovery,

    /// <summary>
    /// Waiting for user input.
    /// </summary>
    Question
}

/// <summary>
/// An option for user selection in a flow (client-side record version).
/// </summary>
public record FlowOption(string Label, string Value, bool IsRecommended = false, string? Preview = null);

/// <summary>
/// A single entry in the setup flow timeline.
/// </summary>
public record FlowStateEntry
{
    /// <summary>
    /// The pipeline stage this entry represents.
    /// </summary>
    public required string Stage { get; init; }

    /// <summary>
    /// Current status of this entry.
    /// </summary>
    public required FlowStateStatus Status { get; init; }

    /// <summary>
    /// Brief summary for display (≤50 chars recommended).
    /// </summary>
    public required string Summary { get; init; }

    /// <summary>
    /// When this entry was created.
    /// </summary>
    public DateTimeOffset Timestamp { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Whether this is the current/active state in the timeline.
    /// </summary>
    public bool IsCurrentState { get; init; }

    /// <summary>
    /// Optional detailed message (for errors or recovery reasoning).
    /// </summary>
    public string? Details { get; init; }

    /// <summary>
    /// For Question status: the input type marker ([YES/NO], [SELECT:...], [INPUT]).
    /// </summary>
    public string? InputType { get; init; }

    /// <summary>
    /// For Question status with SELECT: the available options with label and value.
    /// </summary>
    public List<FlowOption>? Options { get; init; }
}

/// <summary>
/// DTO for flow state entry streamed to the client.
/// Same as FlowStateEntry but as a class for serialization compatibility.
/// </summary>
public class FlowStateEntryDto
{
    public required string Stage { get; set; }
    public FlowStateStatusDto Status { get; set; }
    public required string Summary { get; set; }
    public DateTimeOffset Timestamp { get; set; }
    public bool IsCurrentState { get; set; }
    public string? Details { get; set; }
    public string? InputType { get; set; }
    public List<FlowOptionDto>? Options { get; set; }
}

/// <summary>
/// Status enum for DTOs (mirrors FlowStateStatus).
/// </summary>
public enum FlowStateStatusDto
{
    Pending,
    InProgress,
    Completed,
    Failed,
    Recovery,
    Question
}

/// <summary>
/// An option presented to the user in a flow question.
/// </summary>
public class FlowOptionDto
{
    public required string Label { get; set; }
    public required string Value { get; set; }
    public bool IsRecommended { get; set; }
    public string? Preview { get; set; }
}

/// <summary>
/// A pending setup session awaiting user input.
/// </summary>
public class PendingSetupDto
{
    /// <summary>
    /// The session ID to resume.
    /// </summary>
    public Guid SessionId { get; set; }

    /// <summary>
    /// Display name (typically the URL being configured).
    /// </summary>
    public required string DisplayName { get; set; }

    /// <summary>
    /// The current question awaiting user input.
    /// </summary>
    public string? CurrentPrompt { get; set; }

    /// <summary>
    /// When this session was last active.
    /// </summary>
    public DateTimeOffset LastActivityAt { get; set; }

    /// <summary>
    /// When this session was created.
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; }
}
