using ChangeDetection.Core.Entities;
using Shouldly;

namespace ChangeDetection.Core.Tests.Entities;

[Category("Unit")]
public class WatchedSiteTests
{
    [Test]
    public async Task DefaultValues_ShouldBeCorrect()
    {
        var site = new WatchedSite { Url = "https://example.com" };

        site.CheckInterval.ShouldBe(TimeSpan.FromMinutes(30));
        site.Status.ShouldBe(WatchStatus.Active);
        site.IsEnabled.ShouldBeTrue();
        site.ConsecutiveFailures.ShouldBe(0);
        site.AutoErrorResolutionEnabled.ShouldBeTrue();
        site.AutoResolutionAttempts.ShouldBe(0);
        site.MaxAutoResolutionAttempts.ShouldBe(3);
        site.SchemaEnabled.ShouldBeFalse();
        await Task.CompletedTask;
    }

    [Test]
    public async Task Id_ShouldBeAutoGenerated()
    {
        var site = new WatchedSite { Url = "https://example.com" };

        site.Id.ShouldNotBe(Guid.Empty);
        await Task.CompletedTask;
    }

    [Test]
    public async Task Id_ShouldBeUnique()
    {
        var site1 = new WatchedSite { Url = "https://example.com" };
        var site2 = new WatchedSite { Url = "https://example.com" };

        site1.Id.ShouldNotBe(site2.Id);
        await Task.CompletedTask;
    }

    [Test]
    public async Task OwnerId_ShouldDefaultToGuidEmpty()
    {
        var site = new WatchedSite { Url = "https://example.com" };

        site.OwnerId.ShouldBe(Guid.Empty);
        await Task.CompletedTask;
    }

    [Test]
    public async Task Url_ShouldBeSet()
    {
        var site = new WatchedSite { Url = "https://example.com" };

        site.Url.ShouldBe("https://example.com");
        await Task.CompletedTask;
    }

    [Test]
    public async Task Collections_ShouldDefaultToEmpty()
    {
        var site = new WatchedSite { Url = "https://example.com" };

        site.Tags.ShouldBeEmpty();
        site.TagColors.ShouldBeEmpty();
        site.IgnorePatterns.ShouldBeEmpty();
        site.FilterRules.ShouldBeEmpty();
        site.SelectorHistory.ShouldBeEmpty();
        await Task.CompletedTask;
    }

    [Test]
    public async Task NullableProperties_ShouldDefaultToNull()
    {
        var site = new WatchedSite { Url = "https://example.com" };

        site.Name.ShouldBeNull();
        site.CssSelector.ShouldBeNull();
        site.XPathSelector.ShouldBeNull();
        site.LastChecked.ShouldBeNull();
        site.LastChanged.ShouldBeNull();
        site.LastContentHash.ShouldBeNull();
        site.CategoryId.ShouldBeNull();
        site.Description.ShouldBeNull();
        site.LastError.ShouldBeNull();
        site.Schema.ShouldBeNull();
        site.LlmProviderOverride.ShouldBeNull();
        site.UserIntent.ShouldBeNull();
        site.AverageChangeInterval.ShouldBeNull();
        site.LastIntervalAdjustment.ShouldBeNull();
        site.LastResolutionDiagnosis.ShouldBeNull();
        site.LastResolutionAttempt.ShouldBeNull();
        await Task.CompletedTask;
    }

    [Test]
    public async Task NestedSettings_ShouldBeInitialized()
    {
        var site = new WatchedSite { Url = "https://example.com" };

        site.ScheduleSettings.ShouldNotBeNull();
        site.Notifications.ShouldNotBeNull();
        site.FetchSettings.ShouldNotBeNull();
        site.AnalysisSettings.ShouldNotBeNull();
        await Task.CompletedTask;
    }

    [Test]
    public async Task AnalysisSettings_ShouldHaveCorrectDefaults()
    {
        var site = new WatchedSite { Url = "https://example.com" };
        var settings = site.AnalysisSettings;

        settings.EnableChangeAnalysis.ShouldBeTrue();
        settings.EnableContentEnrichment.ShouldBeFalse();
        settings.GenerateSemanticSummary.ShouldBeTrue();
        settings.CalculateRelevance.ShouldBeTrue();
        settings.ExtractEntities.ShouldBeTrue();
        settings.AnalyzeSentiment.ShouldBeFalse();
        settings.DetectAnomalies.ShouldBeFalse();
        settings.CategorizeChanges.ShouldBeTrue();
        settings.GenerateSuggestedActions.ShouldBeFalse();
        settings.MinRelevanceForNotification.ShouldBeNull();
        settings.OnlyNotifyHighImportance.ShouldBeFalse();
        settings.EnableSemanticDeduplication.ShouldBeFalse();
        settings.SemanticSimilarityThreshold.ShouldBe(0.95f);
        await Task.CompletedTask;
    }

    [Test]
    public async Task CreatedAt_ShouldBeRecentUtc()
    {
        var before = DateTime.UtcNow;
        var site = new WatchedSite { Url = "https://example.com" };
        var after = DateTime.UtcNow;

        site.CreatedAt.ShouldBeGreaterThanOrEqualTo(before);
        site.CreatedAt.ShouldBeLessThanOrEqualTo(after);
        await Task.CompletedTask;
    }
}
